"""
Stale Context Detection & Mitigation POC

Problem: In long-running Claude Code sessions, early messages reference state
that may no longer be true — deleted files, old configs, superseded decisions.
Claude keeps treating stale context as current truth, producing hallucinated
references and contradictory advice.

This POC demonstrates three mitigation strategies:
  1. Timestamp tagging   — every turn carries wall-clock time so the model
                           can reason about recency.
  2. Staleness detection — score each turn by age; flag stale ones.
  3. Context compaction  — ask Claude to summarize old turns into a single
                           message, freeing token budget for fresh context.
"""

import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path

from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

client = Anthropic()
MODEL = os.getenv("MODEL_NAME", "claude-sonnet-4-6")

# Configurable thresholds — surfaced in .env so operators can tune
# without touching code.
STALENESS_THRESHOLD = int(os.getenv("STALENESS_THRESHOLD_SECS", "300"))
MAX_TURNS = int(os.getenv("MAX_TURNS_BEFORE_COMPACTION", "10"))

HISTORY_FILE = Path("session_history.json")


# ---------------------------------------------------------------------------
# Core data structure
# ---------------------------------------------------------------------------

@dataclass
class TimestampedMessage:
    """Every message carries its creation time — without this, the model
    cannot distinguish a 5-second-old fact from a 5-hour-old one."""
    role: str
    content: str
    timestamp: float = field(default_factory=time.time)

    def age_secs(self) -> float:
        return time.time() - self.timestamp

    def is_stale(self, threshold: float = STALENESS_THRESHOLD) -> bool:
        # Age alone is the simplest staleness signal; production systems
        # layer on contradiction detection and file-change watchers.
        return self.age_secs() > threshold

    def to_api_msg(self) -> dict:
        """Inject timestamp into the content so Claude can reason about
        recency even though the API schema has no native timestamp field."""
        age = int(self.age_secs())
        tag = f"[{age}s ago] " if age > 0 else ""
        return {"role": self.role, "content": f"{tag}{self.content}"}

    def to_dict(self) -> dict:
        return {"role": self.role, "content": self.content, "ts": self.timestamp}

    @classmethod
    def from_dict(cls, d: dict) -> "TimestampedMessage":
        return cls(role=d["role"], content=d["content"], timestamp=d["ts"])


# ---------------------------------------------------------------------------
# Session with staleness awareness
# ---------------------------------------------------------------------------

class StaleAwareSession:
    """Manages a conversation that automatically detects and mitigates
    stale context as the session grows."""

    def __init__(self):
        self.messages: list[TimestampedMessage] = []
        self.compaction_count = 0

    # -- Persistence ---------------------------------------------------------

    def save(self) -> None:
        HISTORY_FILE.write_text(
            json.dumps([m.to_dict() for m in self.messages], indent=2)
        )

    def load(self) -> None:
        if HISTORY_FILE.exists():
            self.messages = [
                TimestampedMessage.from_dict(d)
                for d in json.loads(HISTORY_FILE.read_text())
            ]

    # -- Staleness audit -----------------------------------------------------

    def audit(self) -> dict:
        """Return a staleness report — the operator's window into context health."""
        stale = [m for m in self.messages if m.is_stale()]
        return {
            "total_turns": len(self.messages),
            "stale_turns": len(stale),
            "freshness_ratio": (
                round(1 - len(stale) / len(self.messages), 2)
                if self.messages else 1.0
            ),
            "oldest_age_secs": (
                int(max(m.age_secs() for m in self.messages))
                if self.messages else 0
            ),
            "needs_compaction": len(self.messages) >= MAX_TURNS or len(stale) > 0,
        }

    # -- Compaction ----------------------------------------------------------

    def compact(self) -> str:
        """Replace all stale turns with a single summary generated by Claude.
        This is the primary mitigation: old, potentially outdated detail is
        condensed into a short recap, freeing the context window for fresh
        information while preserving key decisions."""

        stale = [m for m in self.messages if m.is_stale()]
        if not stale:
            return "Nothing to compact — all context is fresh."

        # Feed only the stale slice to Claude for summarization.
        summary_prompt = (
            "Summarize the following conversation excerpt into a concise "
            "recap of key decisions and current state. Drop any details that "
            "may have been superseded. Be brief.\n\n"
            + "\n".join(f"{m.role}: {m.content}" for m in stale)
        )

        response = client.messages.create(
            model=MODEL,
            max_tokens=512,
            # System prompt steers the summary toward facts, not chat fluff.
            system="You are a context compactor. Output only the summary.",
            messages=[{"role": "user", "content": summary_prompt}],
        )
        summary = response.content[0].text

        # Rebuild the message list: one synthetic recap + all fresh turns.
        fresh = [m for m in self.messages if not m.is_stale()]
        recap = TimestampedMessage(
            role="assistant",
            # Tag clearly so downstream readers know this is synthetic.
            content=f"[COMPACTED CONTEXT — recap of {len(stale)} earlier turns]\n{summary}",
        )
        self.messages = [recap] + fresh
        self.compaction_count += 1
        self.save()

        return summary

    # -- Chat ----------------------------------------------------------------

    def chat(self, user_text: str) -> str:
        self.messages.append(TimestampedMessage(role="user", content=user_text))

        # Inject recency tags so Claude sees how old each message is —
        # this is the minimal, zero-cost staleness signal.
        api_messages = [m.to_api_msg() for m in self.messages]

        # System prompt warns Claude that old context may be outdated,
        # nudging it to prefer recent information on conflicts.
        system = (
            "You are a helpful coding assistant in a long-running session. "
            "Each message is prefixed with its age. "
            "IMPORTANT: If older messages conflict with newer ones, "
            "trust the newer information — the older context may be stale. "
            "When uncertain about a fact from an old message, say so."
        )

        response = client.messages.create(
            model=MODEL,
            max_tokens=1024,
            system=system,
            messages=api_messages,
        )

        reply = response.content[0].text
        self.messages.append(TimestampedMessage(role="assistant", content=reply))
        self.save()
        return reply


# ---------------------------------------------------------------------------
# Demo: simulate staleness in a compressed time frame
# ---------------------------------------------------------------------------

def run_demo():
    session = StaleAwareSession()

    print("=" * 64)
    print("PHASE 1: Establish initial context (will become stale)")
    print("=" * 64)

    r1 = session.chat(
        "Our main database is PostgreSQL 14, running on db-prod-1. "
        "The config is in /etc/app/db.yaml."
    )
    print(f"  Claude: {r1}\n")

    r2 = session.chat("The API rate limit is 100 req/s, set in nginx.conf.")
    print(f"  Claude: {r2}\n")

    # Artificially age these first messages to simulate hours passing —
    # in real sessions this happens naturally as the user works.
    for m in session.messages:
        m.timestamp -= (STALENESS_THRESHOLD + 60)

    print("=" * 64)
    print("PHASE 2: External state changes — context is now stale")
    print("=" * 64)
    print("  (Simulated: messages aged beyond staleness threshold)\n")

    # New facts contradict the old ones — this is the core problem.
    r3 = session.chat(
        "UPDATE: We migrated to PostgreSQL 16 on db-prod-2 yesterday. "
        "Config moved to /etc/app/db-v2.yaml. "
        "Also, rate limit was raised to 500 req/s."
    )
    print(f"  Claude: {r3}\n")

    print("=" * 64)
    print("PHASE 3: Staleness audit")
    print("=" * 64)

    report = session.audit()
    for k, v in report.items():
        print(f"  {k}: {v}")
    print()

    print("=" * 64)
    print("PHASE 4: Compact stale context")
    print("=" * 64)

    summary = session.compact()
    print(f"  Compacted summary:\n  {summary}\n")

    report_after = session.audit()
    print("  Post-compaction audit:")
    for k, v in report_after.items():
        print(f"    {k}: {v}")
    print()

    print("=" * 64)
    print("PHASE 5: Verify — ask Claude about current state")
    print("=" * 64)

    # The real test: does Claude cite the NEW facts (PG 16, db-prod-2)
    # and not the stale ones (PG 14, db-prod-1)?
    r4 = session.chat(
        "What database version and host are we currently using? "
        "What's the current rate limit?"
    )
    print(f"  Claude: {r4}\n")

    print("=" * 64)
    print("PHASE 6: Session statistics")
    print("=" * 64)
    print(f"  Total turns in context: {len(session.messages)}")
    print(f"  Compactions performed:  {session.compaction_count}")
    final = session.audit()
    print(f"  Freshness ratio:        {final['freshness_ratio']}")


def run_interactive():
    """Interactive mode with staleness commands."""
    session = StaleAwareSession()
    session.load()

    print("\nStale Context Detector — Interactive Mode")
    print("Commands:")
    print("  /audit     — show staleness report")
    print("  /compact   — summarize & remove stale turns")
    print("  /history   — show all turns with ages")
    print("  /reset     — clear session")
    print("  /quit      — exit\n")

    while True:
        user_input = input("You: ").strip()
        if not user_input:
            continue

        if user_input == "/audit":
            report = session.audit()
            for k, v in report.items():
                print(f"  {k}: {v}")

        elif user_input == "/compact":
            summary = session.compact()
            print(f"  Compacted: {summary}")

        elif user_input == "/history":
            for i, m in enumerate(session.messages):
                age = int(m.age_secs())
                stale_tag = " [STALE]" if m.is_stale() else ""
                # Truncate long messages for readability in the terminal.
                preview = m.content[:80] + ("..." if len(m.content) > 80 else "")
                print(f"  [{i}] {m.role} ({age}s ago){stale_tag}: {preview}")

        elif user_input == "/reset":
            session.messages.clear()
            session.save()
            print("  Session cleared.")

        elif user_input == "/quit":
            break

        elif user_input.startswith("/"):
            print("  Unknown command. Try /audit, /compact, /history, /reset, or /quit.")

        else:
            reply = session.chat(user_input)
            print(f"\n  Claude: {reply}\n")


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Stale context detection & mitigation POC"
    )
    parser.add_argument(
        "--demo", action="store_true",
        help="Run the scripted demo instead of interactive mode.",
    )
    args = parser.parse_args()

    if args.demo:
        run_demo()
    else:
        run_interactive()


if __name__ == "__main__":
    main()
